--------------------------------------------------------
--  File created - Monday-June-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISPURUSER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DISPURUSER" 
   (	"USERID" NUMBER(10,0), 
	"USERPWD" VARCHAR2(255 BYTE), 
	"USERGROUP" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CONTACT_NO" VARCHAR2(15 BYTE), 
	"PLANID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.DISPURUSER
SET DEFINE OFF;
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (1001,'123','Relationship Manager','Amir','KL','amir_RM@dispur.com','0132500123',1);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (2001,'123','Operator','Anis','Singapore','anis_OR@dispur.com','9827332',1);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (3001,'123','Admin','Kumar','India','ramu_admin@dispur.com','8827123',1);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (5555,'123','Customer','asa','asdsada','asdad','12313131123',1);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (5900,'123','Customer','raden','raden','KL','01231321313',9125);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (5517,'123','Customer','a','a','a','123123123123',9251);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (5597,'123','Customer','tes','123','test','12312312312',1);
Insert into SYSTEM.DISPURUSER (USERID,USERPWD,USERGROUP,NAME,ADDRESS,EMAIL,CONTACT_NO,PLANID) values (5137,'123','Customer','raden','123','test','12321312311',1);
--------------------------------------------------------
--  DDL for Index SYS_C007109
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007109" ON "SYSTEM"."DISPURUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DISPURUSER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DISPURUSER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISPURUSER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DISPURUSER" ADD FOREIGN KEY ("PLANID")
	  REFERENCES "SYSTEM"."PLAN" ("PLANID") ENABLE;
