--------------------------------------------------------
--  File created - Monday-June-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PLAN" 
   (	"PLANID" NUMBER(10,0), 
	"PLAN_NAME" VARCHAR2(255 BYTE), 
	"TYPE_OF_PLAN" VARCHAR2(255 BYTE), 
	"TARIFF" VARCHAR2(30 BYTE), 
	"VALIDITY" NUMBER(3,0), 
	"RENTAL" NUMBER(6,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PLAN
SET DEFINE OFF;
Insert into SYSTEM.PLAN (PLANID,PLAN_NAME,TYPE_OF_PLAN,TARIFF,VALIDITY,RENTAL) values (1,'NONE','NONE','0/0',0,0);
Insert into SYSTEM.PLAN (PLANID,PLAN_NAME,TYPE_OF_PLAN,TARIFF,VALIDITY,RENTAL) values (9125,'Dispur5G','Data','300/60',90,100.5);
Insert into SYSTEM.PLAN (PLANID,PLAN_NAME,TYPE_OF_PLAN,TARIFF,VALIDITY,RENTAL) values (9251,'Dispur4GMAX','Voice','100/3',300,10.5);
--------------------------------------------------------
--  DDL for Index SYS_C007098
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007098" ON "SYSTEM"."PLAN" ("PLANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PLAN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PLAN" ADD PRIMARY KEY ("PLANID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
